export const FoodItems = [
  {
    id: 1,
    url: "https://flowbite.s3.amazonaws.com/docs/gallery/square/image-1.jpg",
    title: "Sample Title",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 2,
    url: "https://flowbite.s3.amazonaws.com/docs/gallery/square/image-1.jpg",
    title: "Sample Title",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 3,
    url: "https://flowbite.s3.amazonaws.com/docs/gallery/square/image-1.jpg",
    title: "Sample Title",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 4,
    url: "https://flowbite.s3.amazonaws.com/docs/gallery/square/image-1.jpg",
    title: "Sample Title",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 5,
    url: "https://flowbite.s3.amazonaws.com/docs/gallery/square/image-1.jpg",
    title: "Sample Title",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 6,
    url: "https://flowbite.s3.amazonaws.com/docs/gallery/square/image-1.jpg",
    title: "Sample Title",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 7,
    url: "https://flowbite.s3.amazonaws.com/docs/gallery/square/image-1.jpg",
    title: "Sample Title",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 8,
    url: "https://flowbite.s3.amazonaws.com/docs/gallery/square/image-1.jpg",
    title: "Sample Title",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
];

export const orderList = [
  {
    id: 1,
    image: "/ลุย.png",
    title: "เค้กสตอบอแล้",
    Price: 135,
    details: "ไม่ใส่ท้อปปิ้ง",
    qualtity: 1,
  },
  {
    id: 2,
    image: "/ลุย.png",
    title: "คั่วไก่",
    Price: 95,
    details: "ใส่ปลา",
    qualtity: 1,
  },
  {
    id: 3,
    image: "/ลุย.png",
    title: "ชานม",
    Price: 135,
    details: "หวานน้อย",
    qualtity: 1,
  },
  {
    id: 4,
    image: "/ลุย.png",
    title: "ชามะนาว",
    Price: 105,
    details: "ไม่ชา",
    qualtity: 1,
  },
  {
    id: 5,
    image: "/ลุย.png",
    title: "แมว",
    Price: 175,
    details: "สีส้ม",
    qualtity: 1,
  },
  {
    id: 6,
    image: "/ลุย.png",
    title: "ไก่",
    Price: 50,
    details: "สีเขียว",
    qualtity: 1,
  },
  {
    id: 7,
    image: "/ลุย.png",
    title: "นาฟิกา",
    Price: 100,
    details: "ของเพื่อน",
    qualtity: 1,
  },
];
